name: Daily Contributions Workflow x10

on:
  schedule:
    # 10 runs per day at different times (UTC)
    - cron: '0 6 * * *'   # 6:00 AM UTC
    - cron: '0 8 * * *'   # 8:00 AM UTC
    - cron: '0 10 * * *'  # 10:00 AM UTC
    - cron: '0 12 * * *'  # 12:00 PM UTC
    - cron: '0 14 * * *'  # 2:00 PM UTC
    - cron: '0 15 * * *'  # 3:00 PM UTC
    - cron: '0 16 * * *'  # 4:00 PM UTC
    - cron: '0 17 * * *'  # 5:00 PM UTC
    - cron: '0 18 * * *'  # 6:00 PM UTC
    - cron: '0 20 * * *'  # 8:00 PM UTC
  workflow_dispatch:      # allows manual run

permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Ensure contributions file exists
        run: |
          if [ ! -f contributions.md ]; then
            echo "# Contributions Log" > contributions.md
            echo "" >> contributions.md
          fi

      - name: Append today's contribution
        run: |
          TODAY="$(date -u +"%Y-%m-%d %H:%M UTC")"
          echo "- $TODAY : Daily contribution entry" >> contributions.md

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add contributions.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "chore: daily contribution $(date -u +'%Y-%m-%d %H:%M')"
          git push
