name: Daily Contribution Commit x10

on:
  schedule:
    - cron: '0 0 * * *'   # daily at 00:00 UTC
  workflow_dispatch:      # allows manual run

permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Ensure contributions file exists
        run: |
          if [ ! -f contributions.md ]; then
            echo "# Contributions Log" > contributions.md
            echo "" >> contributions.md
          fi

      - name: Make 10 commits
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          for i in {1..10}
          do
            TODAY="$(date -u +"%Y-%m-%d %H:%M UTC")"
            echo "- $TODAY : Daily contribution entry #$i" >> contributions.md
            git add contributions.md
            git commit -m "chore: daily contribution #$i $(date -u +'%Y-%m-%d %H:%M')"
            git push
            sleep 5  # small delay to avoid pushing too quickly
          done
